In [3]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix

In [4]:
"""def MG_calculator(form, scores, options):
        
    details = form.iloc[:, : 5] # n x 4
    MGR = np.array(form.iloc[:, 5 :]) # n x 6

    m, n = form.shape
    final_scores_list = []

    #calculate main good scores

    for i in range(m):
        
        detail = details.iloc[i]
        response = responses_to_sparse_matrix(MGR, options)
        print(f'response is {response}\nscores is {scores}')
        options_with_base_score = np.multiply(response, scores)
        
        final_score = np.sum(options_with_base_score)
        
        final_scores_list.append((detail.iloc[0], detail.iloc[1], detail.iloc[2], detail.iloc[3], detail.iloc[4], final_score))

    MG_scores_df = pd.DataFrame(final_scores_list, columns=["Email address", "Team Name", "Team Leader\'s Name", "Contact Number (Team Leader)", "Email Id (Team Leader)", "Final Score for CG"])

    return MG_scores_df"""

def MG_calculator(form, scores, options):
        
    details = form.iloc[:, : 5] # n x 4
    MGR = np.array(form.iloc[:, 5 :], dtype=str) # n x reamiming questions
    
    m, n = form.shape
    final_scores_list = []

    #calculate main good scores

    for i in range(m):
        
        detail = details.iloc[i]
        response = responses_to_sparse_matrix(MGR[i], options)

        options_with_base_score = np.multiply(response, scores)
        
        final_score = np.sum(options_with_base_score)
        
        final_scores_list.append((detail.iloc[0], detail.iloc[1], detail.iloc[2], detail.iloc[3], detail.iloc[4], final_score))

    MG_scores_df = pd.DataFrame(final_scores_list, columns=["Email Address", "Team Name", "Team Leader\'s Name", "Contact Number (Team Leader)", "Email Id (Team Leader)", "Final Score for MG"])

    return MG_scores_df


def responses_to_sparse_matrix(responses, options):
    
    num_questions = len(responses)
    num_options = len(options)
    
    # Create an empty matrix of zeros
    matrix = np.zeros((num_questions, num_options), dtype=int)
    
    # Fill in the matrix with 1s based on responses
    for q_idx, response in enumerate(responses):
        if response in options:
            opt_idx = options.index(response)
            matrix[q_idx, opt_idx] = 1
    
    # Convert to sparse format
    sparse_matrix = csr_matrix(matrix)
    return sparse_matrix.toarray()

In [5]:
# Load the scores file
df = pd.read_csv('C:/Users/yashu/Desktop/bequest/scores for round 2 - Gaming item.csv')

# Fill empty cells with 0
df_filled = df.fillna(0)

# Extract only numerical values (excluding the first column if it's text)
r2_scores = df_filled.iloc[:, 1:].to_numpy(dtype=float)

print(r2_scores)

[[0. 2. 5. 0. 4. 0. 2. 0.]
 [3. 5. 0. 4. 2. 0. 0. 0.]
 [3. 0. 0. 4. 0. 5. 2. 0.]
 [2. 2. 0. 0. 0. 0. 5. 2.]
 [5. 4. 0. 3. 0. 0. 2. 0.]
 [0. 0. 4. 0. 3. 0. 2. 5.]]


In [6]:
options = ['PS', 'PC', 'Pool', 'Non Electronic Arcade', 'Table Tennis', 'Racing Sim', 'Electronic Arcade', 'VR']
form = pd.read_excel("C:/Users/yashu/Downloads/ROUND-1 BLUEPRINT BATTLE STAGE-2 (Responses) (1).xlsx")

final_scores = MG_calculator(form, r2_scores, options)
display(final_scores)

Email Address                  Team Name  \
0         sujalbnms2004@gmail.com                 Achievers    
1       aditisharma7623@gmail.com            aditisharma7623   
2   kavya2005additional@gmail.com                  AdmiralK    
3          artemisftw14@gmail.com                CRACKHEADS    
4         dhruvaryan302@gmail.com              dhruvaryan302   
5         pmishra_be23@thapar.edu                EVIL J0RDAN   
6       sakshiyadav6359@gmail.com                    Inferno   
7     aishna.chhabra126@gmail.com                innovators    
8             ipm24129@iimj.ac.in                   ipm24129   
9          jioaakash293@gmail.com               Jioaakash293   
10      kamakshidutt264@gmail.com  kamakshidutt264@gmail.com   
11     sankalpsharma250@gmail.com                  LoneWolfs   
12   manandeep.chandhok@gmail.com         manandeep.chandhok   
13   vaibhavmotwani2006@gmail.com                   Maverick   
14    aggarwalmayank343@gmail.com                mayank amin   
15   rahulmalik.srccgbo@gmail.com           Pepsu Consulting   
16       palakverma1404@gmail.com                 Polar Bear   
17      prince.shah4548@gmail.com            prince.shah4548   
18       rajwantyadav07@gmail.com                    Rajwant   
19  niharika.rajput7775@gmail.com                   Selcouth   
20     shashankjatav112@gmail.com                   shashank   
21         snehapal3333@gmail.com               Snehapal3333   
22         malayparag10@gmail.com                   Team Ace   
23            sawrimmi2@gmail.com            The Think Tank    
24           vasundar15@gmail.com                 Vasundar15   

   Team Leader's Name  Contact Number (Team Leader)  \
0              Sujal                     9516968267   
1               Aditi                    8427879350   
2     Kavya Chaudhari                    9354769503   
3      Arya Divyansh                     8271745248   
4        Dhruv Aryan                     7876303864   
5        Parth Mishra                    8299010670   
6        Sakshi Yadav                    9315154643   
7     Aishna chhabra                     6398402024   
8         Vaidik Sahu                    7000257768   
9   Aakash Pastariya                     8770325654   
10      Kamakshi Dutt                    7889781002   
11     Sankalp Sharma                    9616040112   
12    Manandeep Singh                    9810434193   
13    Vaibhav Motwani                    9302611852   
14             Mayank                    8708512670   
15        Rahul Malik                    7984500790   
16        Palak Verma                    9810172295   
17       Prince Kumar                    9818020519   
18      Rajwant Yadav                    7985984175   
19     Niharika Singh                    9910026570   
20           shashank                    8878615992   
21          Sneha Pal                    9873768238   
22        Malay Parag                    7817978237   
23          Rimmi Saw                    7488064892   
24          Vasudevan                    6381658794   

           Email Id (Team Leader)  Final Score for MG  
0         sujalbnms2004@gmail.com                13.0  
1       aditisharma7623@gmail.com                11.0  
2   kavya2005additional@gmail.com                15.0  
3       aryaadivyansh14@gmail.com                17.0  
4         dhruvaryan302@gmail.com                11.0  
5         pmishra_be23@thapar.edu                21.0  
6       sakshiyadav6359@gmail.com                 6.0  
7     aishna.chhabra126@gmail.com                17.0  
8             ipm24129@iimj.ac.in                16.0  
9          jioaakash293@gmail.com                 8.0  
10      kamakshidutt264@gmail.com                14.0  
11     sankalpsharma250@gmail.com                 8.0  
12   manandeep.chandhok@gmail.com                12.0  
13   vaibhavmotwani2006@gmail.com                10.0  
14    aggarwalmayank344@gmail.com                12.0  
15   rahulmalik.srccgbo@gmai

In [7]:
final_scores.to_excel('C:/Users/yashu/Desktop/bequest/round_2_calculated_scores.xlsx')